FROM python:3.11-slim-bookworm

WORKDIR /app/static

COPY requirements-frontend.txt .
RUN python -m venv /venv && \
    /venv/bin/pip install --upgrade pip && \
    /venv/bin/pip install --no-cache-dir -r requirements-frontend.txt

ENV PATH="/venv/bin:$PATH"

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "./static/Home.py", "--server.port=8501", "--server.address=0.0.0.0"]